name: littykitty2
description: "."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  async_builder: ^1.3.1+1
  collection: ^1.17.1
  get_it: ^7.6.4
  rxdart: ^0.27.7
  fast_immutable_collections: ^9.2.0
  nil: ^1.1.1
  comprehensive_utils: ^0.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  async: ^2.11.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  percent_indicator: ^4.2.3
  scrollable_positioned_list: ^0.3.8
  animated_radio_buttons: ^1.0.0
  responsive_framework: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
  assets:
    - assets/bags/
    - assets/cats/
    - assets/